CREATE TABLE `instructor_table` 
    ( `id` INT NOT NULL AUTO_INCREMENT , 
      `instructor` VARCHAR(50) NOT NULL , 
      PRIMARY KEY (`id`)) ENGINE = InnoDB;
 -- sample
INSERT INTO `instructor_table` 
    (`id`, `instructor`) 
VALUES
    (NULL, 'aala, mylen l'),
    (NULL, 'abelleja, ian welbert b'),
    (NULL, 'abrigo, farley l'),
    (NULL, 'acar, gelyn r'),
    (NULL, 'adajar, isedora j'),
    (NULL, 'africa, yolanda d'),
    (NULL, 'alecha, romeo m'),
    (NULL, 'alejar, allan a'),
    (NULL, 'aquino, stanley l'),
    (NULL, 'arcega, john bryan n'),
    (NULL, 'arim, damialto o'),
    (NULL, 'balbaboco, raphael j'),
    (NULL, 'balita, dexter c'),
    (NULL, 'bituin, rosalie a'),
    (NULL, 'bringas, hermogenes jr a'),
    (NULL, 'briones, bryan christian m'),
    (NULL, 'cabrillas, tomas jr l'),
    (NULL, 'callanta, van hector c'),
    (NULL, 'capuno, raegan l'),
    (NULL, 'casabuena, michael m'),
    (NULL, 'castro, sancho d'),
    (NULL, 'catapang, arnold i'),
    (NULL, 'catindig, shiela d'),,
    (NULL, 'cesario, joanne marian b'),
    (NULL, 'chavez, nicolo m'),
    (NULL, 'compasivo, nino a'),
    (NULL, 'contreras, gladycel t'),
    (NULL, 'cruz, jerwin p'),
    (NULL, 'cu, riechell a'),
    (NULL, 'cuasay, bibiana jocelyn d'),
    (NULL, 'david, jaime iv j'),
    (NULL, 'de vera, jhoanna a'),
    (NULL, 'del moral, eva krissele l'),
    (NULL, 'delos reyes, john christian c'),
    (NULL, 'durana, merlita m'),
    (NULL, 'epa, alpha liezel v'),
    (NULL, 'escarez, christopher b'),
    (NULL, 'estrada, jullian paul s'),
    (NULL, 'fajiculay, mark chito d'),
    (NULL, 'fernando, mary may m'),
    (NULL, 'fontarum, jayvee n'),
    (NULL, 'froyalde, loreta l'),
    (NULL, 'galoyo, franklyn'),
    (NULL, 'gamatero, albert n'),
    (NULL, 'gamayon, jesus h'),
    (NULL, 'gamban, nimfa c'),
    (NULL, 'gevana, sherryl m'),
    (NULL, 'guillepa, dessa marie o'),
    (NULL, 'gutierrez, edna h'),
    (NULL, 'hermano, leo d'),
    (NULL, 'julaton, jennet l'),
    (NULL, 'lacorte, alice m'),
    (NULL, 'lajara, richard s'),
    (NULL, 'lazo, marvin gray l'),
    (NULL, 'macabulos, mark nicolas a'),
    (NULL, 'magbuo, jerrylyn b'),
    (NULL, 'magsino, amado l'),
    (NULL, 'magtibay, jen edenelle c'),
    (NULL, 'majadas, dante l'),
    (NULL, 'malabanan, francis a'),
    (NULL, 'malabanan, maricel l'),
    (NULL, 'malolos, lea c'),
    (NULL, 'manalo, lalaine v'),
    (NULL, 'manongsong, rommuelle jester l'),
    (NULL, 'martija, edward van a'),
    (NULL, 'mendoza, arnaldo d'),
    (NULL, 'mojado, ronald d'),
    (NULL, 'monterey, judylen m'),
    (NULL, 'narvacan, irene a'),
    (NULL, 'narvaez, arlyn m'),
    (NULL, 'natividad, reymark r'),
    (NULL, 'oruga, imelda p'),
    (NULL, 'pagcaliwangan, hanzel c'),
    (NULL, 'palis, relly c'),
    (NULL, 'panganiban, teejay d'),
    (NULL, 'pantoja, arthur anthony g'),
    (NULL, 'payne, christopher a'),
    (NULL, 'pecho, bryan c'),
    (NULL, 'pedrosa, benjamin m'),
    (NULL, 'pena, darwin t'),
    (NULL, 'perado, sammy t'),
    (NULL, 'permejo, dinalyn d'),
    (NULL, 'reodica, alfredo c'),
    (NULL, 'ricero, jesus jr. r'),
    (NULL, 'riguera, maria anita a'),
    (NULL, 'rimas, jayson p'),
    (NULL, 'rivera, vincent s'),
    (NULL, 'rulona, adelia a'),
    (NULL, 'sabatin, marvin s'),
    (NULL, 'salazar, jayson s'),
    (NULL, 'salvador, kahrein a'),
    (NULL, 'sandoval, benison r'),
    (NULL, 'santos, adonis s'),
    (NULL, 'sarmiento, pedro gerardo jr v'),
    (NULL, 'sevilla, rovenson v'),
    (NULL, 'shimamura, hiroyuki n'),
    (NULL, 'silva, dulce d'),
    (NULL, 'siman, shirley c'),
    (NULL, 'simyunn, julyvern c'),
    (NULL, 'sorima, jelyn joy s'),
    (NULL, 'sulit, gladys l'),
    (NULL, 'tabing, jay nickson t'),
    (NULL, 'titular, vivian b'),
    (NULL, 'torres, dexter l'),
    (NULL, 'torres, milano o'),
    (NULL, 'umali, melvin b'),
    (NULL, 'velecina, diane cherie m'),
    (NULL, 'villapando, aira sharida h'),
    (NULL, 'yoo, victoria s')
    ;