CREATE TABLE `sched_table`
 -- time are id of time_table
( `id` INT NOT NULL AUTO_INCREMENT , `day` INT NOT NULL , `time` INT NOT NULL ,
    -- rooms data type varchar(size)
    -- id_of_subject id_of_course id_of_instructor id_of_proctor
     `rm210` VARCHAR(100) NULL , `rm211` VARCHAR(100) NULL , `rm212` VARCHAR(100) NULL ,
     `rm213` VARCHAR(100) NULL , `rm214` VARCHAR(100) NULL , `rm215` VARCHAR(100) NULL ,
     `rm216` VARCHAR(100) NULL , `rm301` VARCHAR(100) NULL , `rm302` VARCHAR(100) NULL ,
     `rm303` VARCHAR(100) NULL , `rm304` VARCHAR(100) NULL , `rm305` VARCHAR(100) NULL ,
     `rm306` VARCHAR(100) NULL , `rm307` VARCHAR(100) NULL , `rm308` VARCHAR(100) NULL ,
     `rm309` VARCHAR(100) NULL , `rm310` VARCHAR(100) NULL , `rm311` VARCHAR(100) NULL ,
     `rm312` VARCHAR(100) NULL , `rm313` VARCHAR(100) NULL , `rm314` VARCHAR(100) NULL ,
     `rm315` VARCHAR(100) NULL , `rm316` VARCHAR(100) NULL , `rm317` VARCHAR(100) NULL ,
     `rm318` VARCHAR(100) NULL , `rm401` VARCHAR(100) NULL , `rm406` VARCHAR(100) NULL ,
     `rm409` VARCHAR(100) NULL , `rm410` VARCHAR(100) NULL ,
     `cw1` VARCHAR(100)   NULL , `cw2`   VARCHAR(100) NULL , `cw3`   VARCHAR(100) NULL ,
PRIMARY KEY (`id`)) ENGINE = InnoDB;

INSERT INTO `sched_table` 
    (`id`, `day`, `time`,
        `rm210`, `rm211`, `rm212`, `rm213`, `rm214`, 
        `rm215`, `rm216`, `rm301`, `rm302`, `rm303`, 
        `rm304`, `rm305`, `rm306`, `rm307`, `rm308`, 
        `rm309`, `rm310`, `rm311`, `rm312`, `rm313`, 
        `rm314`, `rm315`, `rm316`, `rm317`, `rm318`, 
        `rm401`, `rm406`, `rm409`, `rm410`, 
        `cw1`, `cw2`, `cw3`) 
VALUES 
    (NULL, '1', '1',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '1', '2',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '1', '3', 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '1', '4',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '1', '5',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '1', '6',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '1', '7',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '1', '8',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '1', '9',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '2', '1',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '2', '2',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '2', '3',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '2', '4',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '2', '5',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '2', '6',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '2', '7',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '2', '8',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '2', '9',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '3', '1',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '3', '2',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '3', '3',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '3', '4',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '3', '5',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '3', '6',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '3', '7',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '3', '8',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL),
    (NULL, '3', '9',
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL)
    ;