CREATE TABLE `section_table` 
    ( `id` INT NOT NULL AUTO_INCREMENT , 
      `section` VARCHAR(50) NOT NULL , 
      PRIMARY KEY (`id`)) ENGINE = InnoDB;
 -- sample
INSERT INTO `section_table` 
    (`id`, `section`) 
VALUES
    (NULL, 'ABMMA 2A'),
    (NULL, 'ABMMA 3A'),
    (NULL, 'BAC-2A'),
    (NULL, 'BAC-3A'),
    (NULL, 'BAC-4A'),
    (NULL, 'BEED GEN-2A'),
    (NULL, 'BEED-3 GENERALIST'),
    (NULL, 'BEED-4 GENERALIST'),
    (NULL, 'BPE-2A'),
    (NULL, 'BPE-3A'),
    (NULL, 'BSA-2A'),
    (NULL, 'BSA-3A'),
    (NULL, 'BSA-4A'),
    (NULL, 'BSACT-2A'),
    (NULL, 'BSACT-3A'),
    (NULL, 'BSACT-4A'),
    (NULL, 'BSBA-EM-SC'),
    (NULL, 'BSBA-EM-2A'),
    (NULL, 'BSBA-EM-3A'),
    (NULL, 'BSBA-EM-4A'),
    (NULL, 'BSBA-MA-2A'),
    (NULL, 'BSBA-MA-3A'),
    (NULL, 'BSBA-MA-4A'),
    (NULL, 'BSCPE-3A'),
    (NULL, 'BSCPE-4A'),
    (NULL, 'BSCPE-5A'),
    (NULL, 'BSCPE-SC'),
    (NULL, 'BSCRIM-2A'),
    (NULL, 'BSCRIM-3A'),
    (NULL, 'BSCRIM-4A'),
    (NULL, 'BSCRIM-SC'),
    (NULL, 'BSCS-2A'),
    (NULL, 'BSCS-3A'),
    (NULL, 'BSCS-4A'),
    (NULL, 'BSECE-3A'),
    (NULL, 'BSECE-4A'),
    (NULL, 'BSECE-5 SC'),
    (NULL, 'BSECE-5A'),
    (NULL, 'BSED-2 ENGLISH'),
    (NULL, 'BSED-2 MATH'),
    (NULL, 'BSED-2MATH'),
    (NULL, 'BSED-3 ENGLISH'),
    (NULL, 'BSED-3 MATH'),
    (NULL, 'BSED-4 ENGLISH'),
    (NULL, 'BSED-4 MATH'),
    (NULL, 'BSHRM-2A'),
    (NULL, 'BSHRM-3A'),
    (NULL, 'BSHRM-4A'),
    (NULL, 'BSHRM4-SC'),
    (NULL, 'BSIE-3A'),
    (NULL, 'BSIE-3SC'),
    (NULL, 'BSIE-4A'),
    (NULL, 'BSIE-5A'),
    (NULL, 'BSIT-2A'),
    (NULL, 'BSIT-2B'),
    (NULL, 'BSIT-3A'),
    (NULL, 'BSIT-3B'),
    (NULL, 'BSIT-4A'),
    (NULL, 'BSIT4-SC'),
    (NULL, 'BSM-2A'),
    (NULL, 'BSM-3A'),
    (NULL, 'BSM-4A'),
    (NULL, 'BSN-2A'),
    (NULL, 'BSN-3A'),
    (NULL, 'BSN-4A'),
    (NULL, 'BSP-1A'),
    (NULL, 'BSP-2A'),
    (NULL, 'BSP-3A'),
    (NULL, 'BSP-4A'),
    (NULL, 'BSP-4SC'),
    (NULL, 'BST-2A'),
    (NULL, 'BST-3A'),
    (NULL, 'BST-4A'),
    (NULL, 'BST-SC'),
    (NULL, 'CPE OLD'),
    (NULL, 'GE-1 SC'),
    (NULL, 'GE-2A'),
    (NULL, 'GE-2B'),
    (NULL, 'ICT-1A'),
    (NULL, 'IE IRR')
    ;